---
ingress:
  enabled: true
  host: olivetin.example.com
  # class: nginx

docker:
  image: docker.io/jamesread/olivetin:2024.02.01

config:

actionsConfig:
  - title: Restart Plex
    icon: smile
    shell: docker restart plex

  # This will send 1 ping
  - title: Ping Google.com
    shell: ping google.com -c 1

persisentVolume: true
