apiVersion: v1
kind: ConfigMap
metadata:
  name: olivetin-config
data:
  config.yaml: |
    {{- if .Values.config }}
    {{ .Values.config | toYaml | nindent 4 }}
    {{- end }}
    actions:
      {{ .Values.actionsConfig | toYaml | nindent 4 }}

