{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: olivetin-ingress
spec:
  {{- if hasKey .Values "ingress.class" }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  defaultBackend: 
    service: 
      name: olivetin
      port:
        number: 1337
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: olivetin
                port:
                  number: 1337
{{- end }}
